# Generated by Django 5.1.4 on 2025-01-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_address_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
