# Generated by Django 5.1.4 on 2025-01-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_age_remove_student_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
    ]
