# Generated by Django 5.1.4 on 2025-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non Veg'), ('Both', 'Both')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
